name: Continuous Deployment to Render

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'models/**'
      - 'requirements.txt'
      - 'Dockerfile'
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy Dockerized API to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Trigger Render Deploy Hook
        run: |
          echo "🚀 Triggering Render deployment..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}