name: 🧪 Run Unit Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (adjust version as needed)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Step 4: Run unit tests
      - name: Run pytest (unit tests)
        run: |
          echo "🚀 Running unit tests..."
          pytest tests/unit/test_train_model -v --disable-warnings --maxfail=3